#!/bin/bash
# setup-worktree.sh - Create worktree with automated port allocation and environment isolation
# Standalone copy at ~/setup-worktree.sh - does not depend on gemini repo scripts

set -euo pipefail

trap 'echo "ERROR: Command failed at line $LINENO with exit code $?" >&2' ERR

BRANCH_NAME=$1
REPO=~/Work/gemini
BASE_PORT=40000

if [ -z "$BRANCH_NAME" ]; then
    echo "Usage: $0 <branch-name>"
    echo "Example: $0 feature/new-feature"
    exit 1
fi

# Sanitize branch name for directory
WORKTREE_DIR=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | cut -c1-50)
COMPOSE_NAME=$(echo "gemini-$(basename "$WORKTREE_DIR")" | tr '[:upper:]' '[:lower:]')
WORKTREE_PATH=~/Work/worktrees/$WORKTREE_DIR

# Find next available port index by scanning for a free port range
# (don't rely on worktree count, which breaks when old worktrees are deleted)
echo "Checking port availability..."
WORKTREE_INDEX=0
while true; do
    OFFSET=$((WORKTREE_INDEX * 10))
    POSTGRES_PORT=$((BASE_PORT + OFFSET + 0))
    MEILISEARCH_PORT=$((BASE_PORT + OFFSET + 1))
    MEILISEARCH_UI_PORT=$((BASE_PORT + OFFSET + 2))
    APP_PORT=$((BASE_PORT + OFFSET + 3))
    REACT_UI_PORT=$((BASE_PORT + OFFSET + 4))

    all_available=true
    for port in $POSTGRES_PORT $MEILISEARCH_PORT $MEILISEARCH_UI_PORT $APP_PORT $REACT_UI_PORT; do
        if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1; then
            all_available=false
            break
        fi
    done

    if $all_available; then
        break
    fi

    WORKTREE_INDEX=$((WORKTREE_INDEX + 1))
    if [ $WORKTREE_INDEX -gt 20 ]; then
        echo "ERROR: Could not find available port range after 20 attempts"
        exit 1
    fi
done

# Create worktree
echo "Creating worktree: $WORKTREE_PATH"
if git -C "$REPO" show-ref --verify --quiet "refs/heads/$BRANCH_NAME" || \
   git -C "$REPO" show-ref --verify --quiet "refs/remotes/origin/$BRANCH_NAME"; then
    echo "Branch '$BRANCH_NAME' exists, checking out existing branch..."
    git -C "$REPO" worktree add "$WORKTREE_PATH" "$BRANCH_NAME"
else
    echo "Creating new branch '$BRANCH_NAME'..."
    git -C "$REPO" worktree add "$WORKTREE_PATH" -b "$BRANCH_NAME"
fi
cd "$WORKTREE_PATH"

# Create root-level .envrc for direnv
echo "Creating root-level .envrc for worktree..."
cat > .envrc <<EOF
# Docker Compose configuration
export COMPOSE_PROJECT_NAME=$COMPOSE_NAME

# Playwright
export PLAYWRIGHT_BASE_URL="http://localhost:$REACT_UI_PORT"

# Load service-api-go .env files
dotenv_if_exists ./service-api-go/.env
dotenv_if_exists ./service-api-go/.env.local
# Load react-ui .env files
dotenv_if_exists ./react-ui/.env
dotenv_if_exists ./react-ui/.env.local

# Load worktree overrides LAST so they take precedence
dotenv_if_exists .env.worktree
EOF

# Create root-level .env.worktree with all configuration
echo "Creating root-level .env.worktree with port assignments..."
cat > .env.worktree <<EOF
# Auto-generated by ~/setup-worktree.sh - DO NOT EDIT MANUALLY
# Recreate worktree or run setup script again to regenerate

# Docker Compose project
COMPOSE_PROJECT_NAME=$COMPOSE_NAME
WORKTREE_INDEX=$WORKTREE_INDEX

# Port assignments (base: $BASE_PORT, offset: $OFFSET)
POSTGRES_PORT=$POSTGRES_PORT
MEILISEARCH_PORT=$MEILISEARCH_PORT
MEILISEARCH_UI_PORT=$MEILISEARCH_UI_PORT
APP_PORT=$APP_PORT

# PostgreSQL configuration
POSTGRES_DB=app
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

# Database URLs (for external/host access)
DATABASE_URL_SUPERUSER=postgresql://postgres:postgres@localhost:$POSTGRES_PORT/app?sslmode=disable
DATABASE_URL_APP=postgresql://app:app@localhost:$POSTGRES_PORT/app?sslmode=disable
DATABASE_URL_BYPASS_RLS=postgresql://bypass-rls:bypass-rls@localhost:$POSTGRES_PORT/app?sslmode=disable

# API configuration - used by air (defaults to app user)
POSTGRESQL_PRIMARY_URI=postgresql://app:app@localhost:$POSTGRES_PORT/app?sslmode=disable
POSTGRESQL_REPLICA_URI=postgresql://app:app@localhost:$POSTGRES_PORT/app?sslmode=disable
POSTGRESQL_BYPASS_RLS_URI=postgresql://bypass-rls:bypass-rls@localhost:$POSTGRES_PORT/app?sslmode=disable
POSTGRESQL_RLS_PRIMARY_URI=postgresql://app:app@localhost:$POSTGRES_PORT/app?sslmode=disable
POSTGRESQL_RLS_REPLICA_URI=postgresql://app:app@localhost:$POSTGRES_PORT/app?sslmode=disable
PORT=$APP_PORT

# Meilisearch configuration
MEILISEARCH_HOST=http://localhost:$MEILISEARCH_PORT
MEILI_ENV=development
MEILI_NO_ANALYTICS=true

# Docker image configuration
DOCKER_COMPOSE_POSTGIS_IMAGE=ghcr.io/cloudnative-pg/postgis:16.11-3.6.1-system-bookworm

# Volume selection (optional, defaults to default_pg_data)
PG_VOLUME=default_pg_data

# React UI configuration
GRAPHQL_URL=http://localhost:$APP_PORT/graphql
REACT_UI_PORT=$REACT_UI_PORT

# NextAuth URLs - must match the port the React dev server is running on
# so FusionAuth redirects back to the correct callback URL
NEXTAUTH_URL=http://localhost:$REACT_UI_PORT
BASE_REACT_URL=http://localhost:$REACT_UI_PORT
EOF
echo "Created .env.worktree"

# Create air tmp directory for service-api-go
mkdir -p service-api-go/tmp

# Copy react-ui/.env.local if it exists in the main worktree
if [ -f "$REPO/react-ui/.env.local" ]; then
    cp "$REPO/react-ui/.env.local" react-ui/.env.local
    echo "react-ui/.env.local copied"
else
    echo "No react-ui/.env.local found in main worktree to copy"
fi

# Install react-ui dependencies
echo "Installing react-ui dependencies..."
cd react-ui
if command -v pnpm >/dev/null 2>&1; then
    pnpm install
    echo "react-ui dependencies installed"
else
    echo "WARNING: pnpm not found. Run 'pnpm install' in react-ui manually."
fi
cd ..

# Download generated code
echo "Downloading generated code from latest main build..."
if (cd "$REPO" && task fetch-generated-code); then
    echo "Generated code downloaded"
else
    echo "Could not download generated code. Run 'task generate' manually."
fi

# Configure direnv
if command -v direnv >/dev/null 2>&1; then
    direnv allow .
    echo "direnv configured"
else
    echo "WARNING: direnv not found. Manually export vars before running docker compose:"
    echo "  set -a && source .env.worktree && set +a"
fi

echo ""
echo "Worktree created: $WORKTREE_PATH"
echo "  PostgreSQL:     localhost:$POSTGRES_PORT"
echo "  Meilisearch:    localhost:$MEILISEARCH_PORT"
echo "  Meilisearch UI: localhost:$MEILISEARCH_UI_PORT"
echo "  API (Go):       localhost:$APP_PORT"
echo "  React UI:       localhost:$REACT_UI_PORT"
echo "  Docker project: $COMPOSE_NAME"
